POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "meon",
    "password": "cedoii",
    "name": "KKKKKK",
    "email": "utem@m.com"
}

###
POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "aizat",
    "password": "123456",
    
}

###
GET http://localhost:3000/

###
GET http://localhost:3000/bye